server:
  port: 8080
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

